name: jd_crazy_x1iu

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_crazy_x1iu
jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 'Run Job'
        run: |
          pip3 install requests
          curl https://raw.githubusercontent.com/fq3/github_x1iu_jd_scripts/master/jd_crazy.py -o jd_crazy_x1iu.py
          python3 jd_crazy_x1iu.py
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          QQ_SKEY: ${{ secrets.QQ_SKEY }}
          QQ_MODE: ${{ secrets.QQ_MODE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
          TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST }}
          TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT }}